### ISSUE TITLE
What's the license of this package

### ISSUE THREAD

**Issue by assafby** [mayconbordin/streaminer#3]
Hi,

I couldn't find the license (if any) under which this package can be used. Can you please clarify?

Thanks,
Assaf

**Comment by mayconbordin** [comment]
It is Apache 2.0

**Comment by saundab** [comment]
Hi, I am seeing a compilation error in "LossyCounting.java" on 
```
@Override
add(T item, long incrementCount)
```
as it is not overriding any existing method. Please advice. Thanks
